---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  This template creates an auto scaling group.

Parameters:
  ImageID: 
    Type: String
    Default: ami-0277155c3f0ab2930

  InstanceType: 
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.    


Resources:
  WebserverLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref ImageID
      InstanceType: !Ref InstanceType
      LaunchConfigurationName: WebserverConfiguration
      UserData: 
        Fn::Base64: 
            !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd.x86_64
              systemctl start httpd.service
              systemctl enable httpd.service
              echo Hello from Udemy Cloudformation course with Rahul $(curl http://169.254.169.254/latest/meta-data/public-ipv4)? > /var/www/html/index.html

  WebserverAutoScale:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: RahulASG
      AvailabilityZones: 
        - us-east-1a
        - us-east-1b
      DesiredCapacity: 2 
      LaunchConfigurationName: !Ref WebserverLaunchConfiguration
      MaxSize: 2
      MinSize: 1
      VPCZoneIdentifier: 
       - subnet-0eb87617710b100e0
       - subnet-068cc54f19ceb2b6c



