AWSTemplateFormatVersion: "2010-09-09"
Description: This is a banking app duh!! It uses S3, API Gateway, and Lambda


Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
        Label: 
          default: "S3 Bucket Name and IAM Role"
        Parameters: 
          - BucketNameParameter
          - LambdaRoleNameParameter

        Label: 
          default: "Lambda Parameters"
        Parameters: 
          - LambdaRuntimeParameter

        Label: 
          default: "API Gateway"
        Parameters: 
          - RESTAPINameParameter
          - APIStageParameter
            

Parameters:
  BucketNameParameter:
    Type: String
    Description: Enter the name of the S3 bucket!

  LambdaRoleNameParameter:
    Type: String
    Description: Enter the name of Lambda IAM Role 

  LambdaRuntimeParameter:
    Type: String
    Default: python3.9
    AllowedValues:
      - python3.7
      - python3.8
      - python3.9
    Description: Lambda runtime. The default is python3.9

  RESTAPINameParameter:
    Type: String
    Description: Enter the name of the REST API 

  APIStageParameter:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - QA
      - Prod
    Description: This is the value of the API Stage

Resources:
  bankings3JE:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParameter

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: IAM Role For Lambda
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      RoleName: !Ref LambdaRoleNameParameter

  bankingRESTAPI: 
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref RESTAPINameParameter

  bankingstatusResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt bankingRESTAPI.RootResourceId
      PathPart: balanceStatus01
      RestApiId: !Ref bankingRESTAPI

  LambdaFunction:
    DependsOn: LambdaExecutionRole
    Type: AWS::Lambda::Function
    Properties:
      Runtime: !Ref LambdaRuntimeParameter
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.lambda_handler
      Code: 
        ZipFile: |
          import json
          import boto3
          
          def lambda_handler(event, context):
              s3_client = boto3.client('s3')
              response = s3_client.get_object(
                  Bucket='dabucket123129',
                  Key='accountBalance.json',
              )
              # convert from streaming data to byte
              data_byte = response['Body'].read()
              # convert from bytes to strings
              data_string = data_byte.decode("UTF-8")
              # convert from json string to dictionary
              data_dict = json.loads(data_string)

              return {
                  'statusCode': 200,
                  'body': json.dumps(data_dict),
                  'headers': {'Content-Type': 'application/json'},
              }
      Description: API Gateway Lambda S3
      Timeout: 60

  bankingstatusMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref bankingRESTAPI
      ResourceId: !Ref bankingstatusResource
      HttpMethod: GET
      MethodResponses:
        - StatusCode: 200
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations'

  APIDeployment:
    DependsOn: bankingstatusMethod
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref bankingRESTAPI
      Description: My deployment to production
      StageName: !Ref APIStageParameter

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceAccount: 374861848262
